### ISSUE TITLE
Security Flaw: SOAP Connection Reuses Session Despite Incorrect Password

### ISSUE THREAD

**Issue by heureka-dev** [a-kbv/php-skype#5]
I've encountered a critical issue with the session management after establishing a connection using SOAP. The bug manifests as follows: once a session file is created during the initial login with the correct credentials via `new Connection($user, $pass)`, this session is persistently returned for any subsequent login attempts made using the same username—even when an incorrect password is provided, as long as the session has not expired.

This behavior poses a significant security vulnerability, especially within a Software as a Service (SaaS) framework. An attacker could potentially gain unauthorized access to a user's Skype data simply by initiating a connection with a known email address while the user's session is active.

**To Reproduce**
1. Perform a successful login to Skype using `new Connection($email, $password, storage_path('skype-sessions'));` with a valid email and password.
2. Attempt to log in again using `new Connection($email, $wrongPassword, storage_path('skype-sessions'));` before the initial session expires, but this time with an incorrect password.
3. Observe that despite the wrong password, the system returns the original session.

**Expected behavior**
The system should invalidate any current sessions and deny access when a login attempt is made with the correct email but an incorrect password. A session should only be created and returned upon successful authentication with both the correct email and password.

**Impact**
This issue compromises user security by not adhering to standard authentication practices, allowing sessions to persist without proper credential verification on subsequent logins.

**Comment by a-kbv** [comment]
Thank you for raising this critical security issue. I understand the potential risk created by the current behavior of session management.

Here's a proposed solution to address and rectify this issue:

1. During a new login attempt with the same username, the system will check if the provided password **matches the one saved in the active session file**.

2. If the passwords do **not match**, the system should **invalidate or delete the session file**.

3. If the passwords do match, let the **session continue**.

4. **Establish a new session** upon successful login.

5. In addition, in order to further strengthen security, I will also work on implementing **encryption for session files**. This makes it more difficult for the content of session files to be maliciously accessed or manipulated. 

These proposed changes will not only prevent unauthorized access to active sessions, but will also make the session data more secure. This aims to resolve the current risk and align the library more closely with standard secure authentication practices.

I appreciate your understanding as I work on implementing these changes. Thank you for your diligence in bringing up this issue and helping make this library more secure.

**Comment by heureka-dev** [comment]
Wow, thanks for the quick turnaround here @a-kbv.

I do have 2 suggestions though for your commit, I've added some comments here for you to consider: https://github.com/a-kbv/php-skype/commit/7b19a89e4c601deff05d1932e67b9b4cf5ab8a1f

Happy to create a PR myself regarding those if you agree.

**Comment by a-kbv** [comment]
Pull requests are welcome.
